site_name: wltr-doc-validate
site_url: https://github.com/walteravelino/wltr-doc-validate
site_description: Pacote para validação de documentos brasileiros.
site_author: MkDocs Team

nav:
    - Instalação: index.md
    - Guia de uso: guia-de-uso.md
    - Sobre: sobre.md
    - Licença: licenca.md

repo_url: https://github.com/walteravelino/wltr-doc-validate

theme: readthedocs
